name: Build images and push to GAR

on:
  workflow_dispatch:
    type: [new-node-image]
  repository_dispatch:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  PROJECT_ID: minimus-sa
  REGION: us-central1
  GAR_LOCATION: us-central1-docker.pkg.dev/minimus-sa/

jobs:
  build-push-artifact:
    runs-on: ubuntu-latest
    steps:

      - name: "Checkout"
        uses: "actions/checkout@v3"
        
      - id: "auth"
        uses: "google-github-actions/auth@v1"
        with:
          credentials_json: "${{ secrets.GCP_SA_KEY }}"

      - name: "Install Cosign"
        uses: sigstore/cosign-installer@v3.8.1

      - name: "Set up Cloud SDK"
        uses: "google-github-actions/setup-gcloud@v1"

      - name: "Use gcloud CLI"
        run: "gcloud info"

      - name: "Minimus registry auth"
        run: docker login -u minimus -p ${{ secrets.MINIMUS_TOKEN }} reg.mini.dev

      - name: "GAR auth"
        run: |-
          gcloud auth configure-docker ${{ env.REGION }}-docker.pkg.dev --quiet
          
      - name: Log into Docker Hub
        uses: docker/login-action@v2.1.0
        with:
          registry: docker.io
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PAT }}
        

           
      - name: Build node image
        run: podman build -t ${{ env.GAR_LOCATION }}node/node-library:latest .

      - name: Build node-mini image
        run: podman build -t ${{ env.GAR_LOCATION }}node/node-mini:latest -f Dockerfile.mini .  
        

      - name: Push node image
        run: podman push ${{ env.GAR_LOCATION }}node/node-library:latest

      - name: Push node-mini image
        run: podman push ${{ env.GAR_LOCATION }}node/node-mini:latest
        
      - name: Scan node image
        uses: aquasecurity/trivy-action@0.31.0
        if: always()
        with:
          image-ref: '${{ env.GAR_LOCATION }}node/node-library:latest'
          format: 'table'

      - name: Scan node-mini image
        uses: aquasecurity/trivy-action@0.31.0
        if: always()
        with:
          image-ref: '${{ env.GAR_LOCATION }}node/node-mini:latest'
          format: 'table'


      - name: Compare Images
        id: docker-scout
        uses: docker/scout-action@v1
        with:
          command: compare
          image: ${{ env.GAR_LOCATION }}node/node-mini:latest
          to: ${{ env.GAR_LOCATION }}node/node-library:latest
          ignore-unchanged: true
          format: markdown
